# -*- coding: utf-8 -*-
"""SQM 재고관리 시스템 버전 정보"""

__version__ = "8.6.5"
VERSION = "8.6.5"
VERSION_TUPLE = (8, 6, 5)
RELEASE_DATE = "2026-04-27"
APP_NAME = "SQM 재고관리 시스템"
APP_NAME_EN = "SQM Inventory Management System"
BUILD_DATE = "2026-04-27"
BUILD_NOTE = (
    "v8.6.4.2 (2026-04-20)\n"
    "Phase 4 — Regression & Hardening\n"
    "  [P1] inventory weight floor INSERT TRIGGER 추가 (음수 방지 강화)\n"
    "  [P4] sold_table UNIQUE INDEX 추가 (중복 SO 삽입 방지)\n"
    "  [THREAD] dashboard _refresh_dashboard_bg thread ID + timing 로깅\n"
    "  [REFACTOR] reserve_from_allocation 466L → 267L (3 helper 추출)\n"
    "  [TEST] pytest 인프라 구축: 10 tests (schema/migration/regression)\n"
    "  [REGRESSION] Phase 3 fix 3건 regression guard 추가\n"
    "  [FIX] run_claude.bat 하드코딩 경로 → %~dp0\n"
    "\n"
    "v8.6.5 (2026-03-31)\n"
    "안정성/효율성/편리성 Phase 2 통합 개선\n"
    "  [STAB-1] process_outbound DB잠금 크래시 방지 (sqlite3 예외 추가)\n"
    "  [STAB-2] transaction() rollback 범위 확대 (Exception 전체)\n"
    "  [STAB-3] confirm_outbound 이중SOLD 체크 실패 시 즉시 차단\n"
    "  [STAB-4] fix_lot_status_integrity N+1 쿼리 제거\n"
    "  [PERF-1] Treeview 일괄 삭제 6곳 (3배 성능 향상)\n"
    "  [PERF-2] Lazy Tab Refresh dirty flag 시스템\n"
    "  [PERF-3] 대시보드 백그라운드 스레드 새로고침\n"
    "  [UX-1] busy cursor (긴 작업 시 대기 표시)\n"
    "  [AUDIT-8] except Exception:pass 7건 → 로깅 교체\n"
    "  [CLEAN-1] inbound_mixin re 중복 import 제거\n"
    "\n"
    "v8.6.4 (2026-03-28)\n"
    "Full audit: 빈except 27건+_log중복 수정\n"
    "Dead code 7개(207줄) 제거\n"
    "서브메서드 12개 추가: inb/ret/co/g1/do/scan 분해\n"
    "인덱스 3개(tb_status_is_sample/sold_delivery/mv_lot_type) 추가\n"
    "파서 v2.7.1: E/F양식+시리얼변환+customs정규화+SC_RCVD\n"
    "\n"
    "v8.6.0 (2026-03-26)\n"
    "MXBG 검증 로직 개선 + N+1 쿼리 제거 (G5)\n"
    "  1) [G5] N+1 제거: 루프 전 IN절 일괄 조회 (LOT N개→fetchall 2회)\n"
    "  2) [G5/G2/LOT모드] COUNT*500→SUM(qty_mt*1000) 하드코딩 제거\n"
    "  3) [G5/G2] STAGED/PENDING_APPROVAL 예약 점유량 포함\n"
    "  4) [allocation_dialog] qty_mt=0 행 차단 (tree sync)\n"
    "\n"
    "v8.5.9 (2026-03-26)\n"
    "입고 UX 개선 + DO 파싱 버그 수정\n"
    "  1) 📁 멀티 선택: Ctrl+클릭으로 BL/PL/FA/DO 한번에 선택\n"
    "     InboundDocDetector 파일명/텍스트 기반 서류 유형 자동 감지\n"
    "     감지 실패 시 선택 순서(BL→PL→FA→DO) fallback\n"
    "  2) 선사 순서 자유화: 파일 선택 후 선사 선택해도 에러 없음\n"
    "     BL 파싱 시 선사 자동 감지 → DB 템플릿 자동 매칭\n"
    "     _auto_match_template_by_carrier: carrier_id/template_id 매칭\n"
    "     PL/INV 힌트 동적 교체 (템플릿 bag_weight/hint 자동 적용)\n"
    "  3) DO 좌표파서 free_time_info 누락 버그 수정 (CON RETURN/FREE TIME 공란 원인)\n"
    "     MSC/MAERSK/carrier_rule 좌표 파서 3곳에 free_time_info 생성 추가\n"
    "     _fill_do가 free_time_info를 읽어 CON RETURN·FREE TIME 계산\n"
    "  4) Allocation 중복 LOT 오판 버그 수정\n"
    "     본제품+샘플(0.001MT) 2행은 정상 허용 (QTY < 0.01 = 샘플)\n"
    "     본제품 행이 2개 이상인 LOT만 진짜 중복으로 제외\n"
    "  5) INVALID_SALE_REF 차단 → 경고로 완화\n"
    "     sale_ref 없어도 예약 진행 (continue 제거, warning만 기록)\n"
    "  6) MXBG 초과 오판 수정 (G5/G2 검증)\n"
    "     MXBG 총량 쿼리에 샘플(is_sample) 포함 → 톤백+샘플 = LOT 전체 가용량\n"
    "     본제품 10개(5,000kg) + 샘플 1개(1kg) = 5,001kg ≤ 5,001kg → 정상 통과\n"
    "  7) 샘플 행 STAGED 충돌 수정 (AL-10-FIX)\n"
    "     샘플 요청 시 일반 톤백 STAGED 카운트 스킵 (전용 is_sample=1 행 배정)\n"
    "     STAGED 쿼리에 qty_mt >= 0.01 조건 추가 (샘플 plan 행 제외)\n"
    "\n"
    "v8.5.7 (2026-03-26)\n"
    "파싱 통합: v856 패치 (CON RETURN/FREE TIME, MSC FA 좌표,\n"
    "  BL containers/GW 보강, Picking Outbound ID, PL import os)\n"
    "출고 보고서: sold_table INSERT 20필드 보강 + 마이그레이션\n"
    "  Detail of Outbound (Excel+PDF) + Sales order DN (Excel+PDF)\n"
    "  메뉴 옵션 10(Outbound Report) + 11(Sales Order DN)\n"
    "\n"
    "v8.5.6 (2026-03-26)\n"
    "P2 안정화: tonbag_move_log WARNING 수정 (self.db→self)\n"
    "P2 교차검증 최적화: 오탐 5개 SKIP 플래그 비활성화\n"
    "  (Net/Gross Weight, Container수/번호, Package수)\n"
    "  BL No: FA 제외 → BL↔DO만 비교\n"
    "  Vessel: BL↔DO 환적 감지만 유지\n"
    "\n"
    "v8.5.5 (2026-03-25)\n"
    "P1 코드베이스 정리: 사문 파일 삭제 (~13,800줄 제거)\n"
    "  - 루트 잔류 패치 파일 6개 삭제 (auto_tooltip, ui_constants,\n"
    "    onestop_inbound, candidate_patch, audit_report, PATCH_README)\n"
    "  - 참조 0건 사문 모듈 삭제:\n"
    "    core/barcode_label_generator, parsers/msc_do_parser,\n"
    "    parsers/maersk_do_parser, parsers/do_dispatcher,\n"
    "    engine_modules/integrity_engine,\n"
    "    features/pdf_parser/pdf_field_extractor,\n"
    "    dialogs/Claude_allocation_stress_test_v712\n"
    "  - sqm_parsing_runtime/ 폴더 전체 삭제 (운영 미사용)\n"
    "  - files/ 폴더 전체 삭제 (구버전 패치 백업)\n"
    "  - 비코드 파일 삭제 (스크린샷, 로그, PATCH_README)\n"
    "\n"
    "v8.5.4 (2026-03-25)\n"
    "HOTFIX: ui_constants.py — import tkinter as tk docstring 밖으로 이동\n"
    "HOTFIX: export_mixin.py — _export_ruby_format 내 import pandas as pd 추가\n"
    "\n"
    "v8.4.0 FULL (2026-03-24)\n"
    "\n"
    "=== v8.1.6~7 (UI/버그) ===\n"
    "BUG-A: 출고취소 OUTBOUND/SOLD 병행조회\n"
    "BUG-B: _alloc_fallback 차단 제거 (취소버튼 3곳)\n"
    "BUG-C: _safe_call 중복except 수정\n"
    "MOVE: 바코드 스캔이동 탭 신규\n"
    "DB: tonbag_move_log + v8.1.7 마이그레이션\n"
    "\n"
    "=== v8.1.8 (UI 표준화) ===\n"
    "BUG-THEME: 테마 레이스컨디션 수정\n"
    "UI: Spacing.Tab 표준상수 / 탭 헤더 통일\n"
    "UTIL: parse_date_range / build_date_sql\n"
    "PATCH: filedialog parent= 46곳\n"
    "PATCH: 창크기저장 11곳 / 스크롤바 4곳\n"
    "\n"
    "=== v8.1.9 (Footer/대시보드) ===\n"
    "FOOTER: TreeviewTotalFooter 색상 개선\n"
    "FOOTER: 합계Footer 신규 19곳\n"
    "DASHBOARD: 전면개편 3구역 구조\n"
    "  1구역: 재고상태카드 5개\n"
    "  2구역: 정합성신호등+알림패널\n"
    "  3구역: 제품별현황테이블\n"
    "\n"
    "=== v8.2.0 (Phase 1+2 시스템 감사) ===\n"
    "SAFETY: 트랜잭션 빈 except 수정\n"
    "SAFETY: gemini_db_corrector DB 어댑터 주입\n"
    "ARCH: DB 경로 config.DB_PATH 단일화 (7곳)\n"
    "ARCH: files/ 패치 파일 README 명시\n"
    "\n"
    "=== v8.2.1 (Phase 3 성능) ===\n"
    "PERF: N+1 쿼리 최적화 7곳\n"
    "  dashboard 14쿼리→2쿼리 (GROUP BY)\n"
    "  outbound_mixin bulk_cancel pre-fetch\n"
    "  return_mixin pre-fetch\n"
    "  validators 배치 UPDATE\n"
    "  advanced_dialogs pre-fetch\n"
    "  outbound_handlers 2N→2쿼리\n"
    "  inbound_handlers pre-fetch\n"
    "INFRA: query_mixin 공통 메서드 4개 추가\n"
    "\n"
    "=== v8.2.2 (Phase 4+6 코드 품질) ===\n"
    "DEAD: Dead code 27개 제거\n"
    "  구버전 마이그레이션, 미사용 helper,\n"
    "  미사용 AI호출, legacy 메서드,\n"
    "  dashboard stub 12개\n"
    "QUALITY: 운영코드 print() 0개 확인\n"
    "\n"
    "=== v8.2.4 (파서 강화) ===\n"
    "PARSER: D/O Dispatcher 선사 자동 판별 라우팅\n"
    "  MEDU*/MSCU* → MSC, MAEU*/MRKU* → Maersk\n"
    "PARSER: do_mixin SQM DOData 통합 반환\n"
    "PARSER: msc carrier_templates 좌표 파서\n"
    "DB: parsing_log 통계 테이블 신규\n"
    "HOTFIX: auto_tooltip.py NameError 수정\n"
    "  _patched_menu_init 미정의→클로저 삽입\n"
    "\n"
    "=== v8.3.0 (Phase 9~11 감사/운영) ===\n"
    "NEW: audit_helper.py — LOT 처리 이력 감사 로그 중앙화\n"
    "  INBOUND/OUTBOUND/RESERVED/RETURN/LOT_UPDATE/LOT_DELETE\n"
    "  inbound_mixin, outbound_mixin, crud_mixin, return_mixin 연동\n"
    "NEW: migration_manager.py — Alembic 스타일 DB 마이그레이션\n"
    "  schema_version 테이블 / 멱등성 보장 (IF NOT EXISTS)\n"
    "  db_schema_mixin 연동 — 앱 시작 시 자동 버전 동기화\n"
    "NEW: error_notifier.py — 에러 이메일 알림 모듈\n"
    "  정합성 오류 / 파싱 실패 알림\n"
    "NEW: daily_report.py — 일별 처리 건수·무게 자동 리포트\n"
    "  엑셀 저장 + 이메일 전송 + 스케줄러 연동\n"
    "ALLOC: allocation_approval_dialog 승인/반려 audit_log 기록\n"
    "ALLOC: workflow_status SQL 문자열→상수 교체\n"
    "DASH: 파싱 실패율 경고 (최근 7일 30% 초과 시)\n"
    "DASH: Allocation 승인 대기 배지\n"
    "TEST: test_v830_phase9_11.py 30개 (P9A~P11)\n"
    "\n"
    "=== v8.3.1 (UX 즉시 출고) ===\n"
    "UX: 재고 탭 우클릭 → '즉시 출고 (원스톱)' 메뉴 추가\n"
    "  inventory_tab 우클릭 컨텍스트 메뉴 확장\n"
    "  onestop_outbound initial_lot_no 자동 채우기\n"
    "UX: 고객사 콤보박스 + Sale Ref 빠른 입력 (출고)\n"
    "FIX: gemini_db_corrector db_adapter 우선, sqlite3 fallback\n"
    "PERF: validators N+1 → 배치 pre-fetch (BL free_time)\n"
    "\n"
    "=== v8.3.2 (출고 UX 강화) ===\n"
    "UX: onestop_outbound 고객사 빠른 선택 UI\n"
    "  콤보박스 선택 시 붙여넣기 란 자동 업데이트\n"
    "\n"
    "=== v8.3.3 (PRO DARK 테마) ===\n"
    "THEME: ui_constants PRO DARK 테마 전면 재설계\n"
    "  Flexport/Linear/Vercel 디자인 기준\n"
    "  Slate-900 배경 + Cyan-400 강조 + 색맹 대응\n"
    "  Status 행 배경색 개선 (채도↓ 명도차↑)\n"
    "UX: onestop_inbound 상단 진행 단계 표시 (Flexport 스타일)\n"
    "  4단계: 서류선택→파싱실행→결과확인→DB저장\n"
    "MENU: menu_registry 물류 앱 기준 재편\n"
    "  핵심 동작(PDF입고/엑셀입고) 우선, 관리 기능 후단\n"
    "\n"
    "=== v8.4.0 (Phase 8 웹 계획) ===\n"
    "DOC: Phase8_Web_개발계획서.md\n"
    "  NiceGUI 웹 조회 화면 확정 (React B안 폐기)\n"
    "  tkinter 병행 + NiceGUI 읽기전용 조회\n"
    "  sqm_web/ 뼈대 존재 (theme.py 100%)\n"
    "FIXTURE: sqm_scenario_data.py 테스트 데이터 확장\n"
    "\n"
    "=== v8.4.2 (템플릿 매핑 핫픽스) ===\n"
    "FIX-SAP: T03 Manual Inbound SAP NO 앞자리 0 소실 버그 수정\n"
    "  import_handlers + inbound_handlers _read_inbound_excel_with_header\n"
    "  dtype={SAP NO:str, LOT NO:str, BL NO:str, CONTAINER:str} 적용\n"
    "FIX-REG: column_registry 한글 alias 추가\n"
    "  arrival_date += '입고일', '입항일'\n"
    "  outbound_date += '출고일'\n"
)
