"""
v864.4 Phase 6 — PyInstaller EXE 빌드 자동화
=============================================

단일 실행: python scripts/build_exe.py
옵션:
    --clean      기존 build/dist 삭제 후 재빌드 (기본)
    --skip-clean 기존 build 유지 (빠른 증분)
    --no-test    빌드 후 EXE 실행 테스트 생략

결과:
    - dist/SQM_v864_4.exe
    - SQM_v864_4.spec (PyInstaller 스펙)
    - REPORTS/phase6_build_<ts>.log

종료 코드:
    0 — 빌드 + 실행 테스트 성공
    1 — 빌드 실패
    2 — 빌드는 성공했으나 실행 테스트 실패
"""
from __future__ import annotations

import argparse
import io
import os
import shutil
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

if sys.stdout.encoding and sys.stdout.encoding.lower() != "utf-8":
    try:
        sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding="utf-8", errors="replace")
    except Exception:
        pass

PROJECT_ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = PROJECT_ROOT / "SQM_v864_4.spec"
DIST_PATH = PROJECT_ROOT / "dist"
BUILD_PATH = PROJECT_ROOT / "build"
EXE_PATH = DIST_PATH / "SQM_v864_4.exe"
LOG_DIR = PROJECT_ROOT / "REPORTS"


SPEC_CONTENT = r'''# -*- mode: python ; coding: utf-8 -*-
# SQM v864.4 PyInstaller spec (auto-generated by scripts/build_exe.py)

from PyInstaller.utils.hooks import collect_all, collect_submodules

# ──────────────────────────────────────────────
# 1. 데이터 파일 (frontend, config 등)
# ──────────────────────────────────────────────
datas = [
    ('frontend', 'frontend'),
    ('config.py', '.'),
    ('config_logging.py', '.'),
    ('config_sql.py', '.'),
]

# ──────────────────────────────────────────────
# 2. Hidden imports — PyInstaller 가 자동 탐지 못하는 서브모듈
# ──────────────────────────────────────────────
hiddenimports = []
for pkg in ('engine_modules', 'features', 'parsers', 'backend'):
    hiddenimports += collect_submodules(pkg)

# 추가 런타임 모듈
hiddenimports += [
    'fastapi',
    'uvicorn.lifespan.on',
    'uvicorn.lifespan.off',
    'uvicorn.protocols.websockets.auto',
    'uvicorn.protocols.websockets.wsproto_impl',
    'uvicorn.protocols.http.auto',
    'uvicorn.protocols.http.h11_impl',
    'uvicorn.protocols.http.httptools_impl',
    'uvicorn.loops.auto',
    'uvicorn.loops.asyncio',
    'pandas',
    'openpyxl',
    'webview',
    'webview.platforms.winforms',
    'clr',
    'clr_loader',
]

# ──────────────────────────────────────────────
# 3. collect_all — 필수 바이너리/데이터 포함 (pandas, openpyxl, webview)
# ──────────────────────────────────────────────
binaries = []
for pkg in ('pandas', 'openpyxl', 'webview'):
    try:
        pd, pb, ph = collect_all(pkg)
        datas += pd
        binaries += pb
        hiddenimports += ph
    except Exception as _e:
        print(f'[spec] collect_all {pkg} 실패 (무시): {_e}')

# ──────────────────────────────────────────────
# 4. Analysis
# ──────────────────────────────────────────────
a = Analysis(
    ['main_webview.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
        'matplotlib',
        'tkinter.test',
        'pytest',
        'black',
        'IPython',
        'jupyter',
    ],
    noarchive=False,
)

pyz = PYZ(a.pure)

# ──────────────────────────────────────────────
# 5. EXE (onefile mode)
# ──────────────────────────────────────────────
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='SQM_v864_4',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,             # UPX 압축 안 함 (Windows Defender 오탐 방지)
    runtime_tmpdir=None,
    console=False,         # --noconsole (frozen stdout 은 main_webview.py 에서 처리)
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=r'frontend/favicon.ico' if __import__('os').path.exists('frontend/favicon.ico') else None,
)
'''


def log(msg: str, tee_handle=None):
    print(msg, flush=True)
    if tee_handle:
        tee_handle.write(msg + "\n")
        tee_handle.flush()


def clean_build_dirs(tee):
    log("\n[1] 이전 빌드 산출물 정리", tee)
    for d in (BUILD_PATH, DIST_PATH):
        if d.exists():
            log(f"  - {d} 삭제 중...", tee)
            shutil.rmtree(d, ignore_errors=True)


def check_pyinstaller(tee) -> bool:
    log("\n[2] PyInstaller 확인", tee)
    try:
        r = subprocess.run(
            [sys.executable, "-m", "PyInstaller", "--version"],
            capture_output=True, text=True, timeout=30,
        )
        if r.returncode == 0:
            log(f"  PyInstaller {r.stdout.strip()} OK", tee)
            return True
    except Exception as e:
        log(f"  체크 실패: {e}", tee)

    log("  ⚠️ PyInstaller 미설치 — 설치 시도", tee)
    r = subprocess.run(
        [sys.executable, "-m", "pip", "install", "--upgrade", "pyinstaller>=6.0"],
        timeout=300,
    )
    if r.returncode != 0:
        log("  ❌ PyInstaller 설치 실패", tee)
        return False
    log("  PyInstaller 설치 완료", tee)
    return True


def write_spec(tee):
    log("\n[3] PyInstaller spec 파일 생성", tee)
    SPEC_PATH.write_text(SPEC_CONTENT, encoding="utf-8")
    log(f"  생성: {SPEC_PATH}", tee)


def run_pyinstaller(tee) -> bool:
    log("\n[4] PyInstaller 빌드 시작 (10~30분 소요)", tee)
    log("  명령: pyinstaller SQM_v864_4.spec --clean --noconfirm", tee)
    start = time.time()
    proc = subprocess.Popen(
        [sys.executable, "-m", "PyInstaller",
         str(SPEC_PATH), "--clean", "--noconfirm",
         "--distpath", str(DIST_PATH),
         "--workpath", str(BUILD_PATH)],
        cwd=str(PROJECT_ROOT),
        stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
        text=True, encoding="utf-8", errors="replace",
    )
    for line in proc.stdout:
        tee.write(line)
        tee.flush()
        # 주요 라인만 콘솔 출력
        if any(k in line for k in ("ERROR", "WARNING:", "INFO: Building", "completed successfully")):
            print(line.rstrip(), flush=True)
    proc.wait()
    elapsed = time.time() - start
    log(f"\n  빌드 시간: {elapsed:.1f}초 ({elapsed/60:.1f}분)", tee)

    if proc.returncode != 0:
        log(f"  ❌ PyInstaller 실패 (exit {proc.returncode})", tee)
        return False

    if not EXE_PATH.exists():
        log(f"  ❌ EXE 파일 없음: {EXE_PATH}", tee)
        return False

    size_mb = EXE_PATH.stat().st_size / (1024 * 1024)
    log(f"  ✅ EXE 생성: {EXE_PATH} ({size_mb:.1f} MB)", tee)
    if size_mb < 30:
        log(f"  ⚠️ 크기 의심 — 너무 작음 ({size_mb:.1f} MB). 일반 80~150 MB", tee)
    return True


def test_exe(tee) -> bool:
    log("\n[5] EXE 실행 테스트 (10초 대기 후 /api/health 호출)", tee)
    import urllib.error
    import urllib.request

    proc = None
    try:
        proc = subprocess.Popen(
            [str(EXE_PATH)],
            cwd=str(DIST_PATH),
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
        )
        log(f"  EXE 실행 (PID {proc.pid}), 10초 대기...", tee)
        time.sleep(10)

        if proc.poll() is not None:
            log(f"  ❌ EXE 가 10초 내 종료됨 (exit {proc.returncode})", tee)
            return False

        try:
            r = urllib.request.urlopen("http://127.0.0.1:8765/api/health", timeout=5)
            if r.status == 200:
                log("  ✅ API /api/health → 200 OK", tee)
                return True
            log(f"  ❌ API 비정상 응답 {r.status}", tee)
            return False
        except urllib.error.URLError as e:
            log(f"  ❌ API 호출 실패: {e}", tee)
            return False
    finally:
        if proc and proc.poll() is None:
            log("  EXE 종료 신호", tee)
            try:
                proc.terminate()
                proc.wait(timeout=10)
            except Exception:
                proc.kill()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--skip-clean", action="store_true", help="기존 build/dist 유지")
    parser.add_argument("--no-test", action="store_true", help="빌드 후 EXE 실행 테스트 생략")
    args = parser.parse_args()

    LOG_DIR.mkdir(exist_ok=True)
    ts = datetime.now().strftime("%Y%m%d_%H%M%S")
    log_path = LOG_DIR / f"phase6_build_{ts}.log"

    with open(log_path, "w", encoding="utf-8") as tee:
        log("=" * 70, tee)
        log(" v864.4 Phase 6 — PyInstaller EXE 빌드", tee)
        log(f" 시작: {datetime.now().isoformat(timespec='seconds')}", tee)
        log(f" 프로젝트: {PROJECT_ROOT}", tee)
        log("=" * 70, tee)

        if not args.skip_clean:
            clean_build_dirs(tee)

        if not check_pyinstaller(tee):
            return 1

        write_spec(tee)

        if not run_pyinstaller(tee):
            log(f"\n로그: {log_path}", tee)
            return 1

        if not args.no_test:
            if not test_exe(tee):
                log(f"\n⚠️ 빌드는 성공했으나 실행 테스트 실패 — 수동 확인 필요", tee)
                log(f"로그: {log_path}", tee)
                return 2

        log("\n" + "=" * 70, tee)
        log(" 🏆 Phase 6 완료", tee)
        log(f" EXE: {EXE_PATH}", tee)
        log(f" 로그: {log_path}", tee)
        log("=" * 70, tee)
        return 0


if __name__ == "__main__":
    sys.exit(main())
